//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> sentDate { get; set; }
        public Nullable<int> messageId { get; set; }
        public string message { get; set; }
        public string appointmentId { get; set; }
        public string recipientPhone { get; set; }
        public Nullable<int> repeatCount { get; set; }
        public string serviceId { get; set; }
        public string sentState { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
